export default Object.freeze({
    OPEN_FILTER_PANEL:     'OPEN_FILTER_PANEL',
    CLOSE_FILTER_PANEL:    'CLOSE_FILTER_PANEL',
    SHOW_BUTTON_UP:        'SHOW_BUTTON_UP',
    HIDE_BUTTON_UP:        'HIDE_BUTTON_UP',
    ADD_NEWS_IN_VIEW:      'ADD_NEWS_IN_VIEW',
    RESET_NEWS_IN_VIEW:    'RESET_NEWS_IN_VIEW',
    UPDATE_NEWS:           'UPDATE_NEWS',
    CLEAR_NEWS_UPDATE:     'CLEAR_NEWS_UPDATE',
    SET_QUANTITY_NEW_NEWS: 'SET_QUANTITY_NEW_NEWS'
});
