export default Object.freeze({
    START_FETCHING:        'START_FETCHING',
    STOP_FETCHING:         'STOP_FETCHING',
    FETCH_SOURCES:         'FETCH_SOURCES',
    FETCH_SOURCES_SUCCESS: 'FETCH_SOURCES_SUCCESS',
    FETCH_SOURCES_FAIL:    'FETCH_SOURCES_FAIL',
    FETCH_NEWS:            'FETCH_NEWS',
    FETCH_NEWS_SUCCESS:    'FETCH_NEWS_SUCCESS',
    FETCH_NEWS_FAIL:       'FETCH_NEWS_FAIL',
    FILL_DEFAULT_SOURCES:  'FILL_DEFAULT_SOURCES'
});
